# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ foil_name: 'Chicago' }, { foil_name: 'Copenhagen' }])
#   Mayor.create(foil_name: 'Emanuel', city: cities.first)

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ foil_name: 'Chicago' }, { foil_name: 'Copenhagen' }])
#   Mayor.create(foil_name: 'Emanuel', city: cities.first)

Name.create(foil_name:'Abrasion Guard SPF', pigment_code:'GCF-214')
Name.create(foil_name:'Apple Green', pigment_code:'GCS-196')
Name.create(foil_name:'Arctic White', pigment_code:'GCS-710')
Name.create(foil_name:'Black (Regular)', pigment_code:'GCS-12')
Name.create(foil_name:'Blue Medal', pigment_code:'GCM-747')
Name.create(foil_name:'Burgundy', pigment_code:'GCS-58')
Name.create(foil_name:'Champagne Gold', pigment_code:'GCS-601')
Name.create(foil_name:'Cherry Red', pigment_code:'G266')
Name.create(foil_name:'Cobalt Blue', pigment_code:'GCS-37')
Name.create(foil_name:'Copper', pigment_code:'GCS-629')
Name.create(foil_name:'Dark Green', pigment_code:'GCS-56')
Name.create(foil_name:'Dark Grey', pigment_code:'GCS-641')
Name.create(foil_name:'Fireball Red', pigment_code:'GCS-393')
Name.create(foil_name:'Flood Coat White', pigment_code:'GCX-10')
Name.create(foil_name:'Flourescent Pink', pigment_code:'GCX-413')
Name.create(foil_name:'Flourescent Red Orange', pigment_code:'GCX-414')
Name.create(foil_name:'Forest Green', pigment_code:'GCS-66')
Name.create(foil_name:'Frog Skin', pigment_code:'G425')
Name.create(foil_name:'Gold', pigment_code:'GCS-631')
Name.create(foil_name:'Gold Medal', pigment_code:'GCM-731')
Name.create(foil_name:'Green', pigment_code:'GCS-186')
Name.create(foil_name:'Grey (Regular)', pigment_code:'GCS-31')
Name.create(foil_name:'Imitation Gold', pigment_code:'GCS-105')
Name.create(foil_name:'Intense Blue', pigment_code:'GCS-47')
Name.create(foil_name:'Jet Black', pigment_code:'GCX-12')
Name.create(foil_name:'Kelly Green', pigment_code:'GCS-46')
Name.create(foil_name:'Lemon Yellow', pigment_code:'GCS-155')
Name.create(foil_name:'Light Grey', pigment_code:'GCS-681')
Name.create(foil_name:'Matte Clear', pigment_code:'GCF-334')
Name.create(foil_name:'Mirror Gold', pigment_code:'F233a')
Name.create(foil_name:'Mirror Silver', pigment_code:'F234')
Name.create(foil_name:'Navy', pigment_code:'GCS-627')
Name.create(foil_name:'Olympic Blue', pigment_code:'GCS-57')
Name.create(foil_name:'Orange', pigment_code:'GCS-14')
Name.create(foil_name:'Periwinkle', pigment_code:'F238')
Name.create(foil_name:'Pink', pigment_code:'GCS-643')
Name.create(foil_name:'Process Pro Cyan', pigment_code:'GCP-807')
Name.create(foil_name:'Process Pro Magenta ', pigment_code:'GCP-873')
Name.create(foil_name:'Process Pro Yellow', pigment_code:'GCP-805')
Name.create(foil_name:'Purple', pigment_code:'GCS-38')
Name.create(foil_name:'Raspberry', pigment_code:'GCS-133')
Name.create(foil_name:'Red Medal', pigment_code:'GCM-783')
Name.create(foil_name:'Royal Reflex', pigment_code:'GCS-687')
Name.create(foil_name:'Ruby Red', pigment_code:'GCS-53')
Name.create(foil_name:'Safety Red', pigment_code:'F228')
Name.create(foil_name:'Silver', pigment_code:'GCS-620')
Name.create(foil_name:'Silver Medal II', pigment_code:'GCM-721')
Name.create(foil_name:'Spectra Shade', pigment_code:'GCX-111')
Name.create(foil_name:'Sunflower Yellow', pigment_code:'GCS-625')
Name.create(foil_name:'Tan', pigment_code:'GCS-39')
Name.create(foil_name:'Teal', pigment_code:'GCS-96')
Name.create(foil_name:'Terra Cotta', pigment_code:'GCS-24')
Name.create(foil_name:'Tomato Red', pigment_code:'GCS-13')
Name.create(foil_name:'Traffic Grey', pigment_code:'GCS-151')
Name.create(foil_name:'Transparent Blue', pigment_code:'GCT-617')
Name.create(foil_name:'Transparent Burgundy', pigment_code:'GCT-49')
Name.create(foil_name:'Transparent Gold', pigment_code:'GCT-105')
Name.create(foil_name:'Transparent Green', pigment_code:'GCT-116')
Name.create(foil_name:'Transparent Orange', pigment_code:'GCT-14')
Name.create(foil_name:'Transparent Plum Purple', pigment_code:'GCT-128')
Name.create(foil_name:'Transparent Red', pigment_code:'GCT-643')
Name.create(foil_name:'Transparent Sapphire Blue', pigment_code:'GCT-37')
Name.create(foil_name:'Transparent Tomato Red', pigment_code:'GCT-13')
Name.create(foil_name:'Transparent Yellow', pigment_code:'GCT-625')
Name.create(foil_name:'Violet Purple', pigment_code:'GCS-628')
Name.create(foil_name:'White', pigment_code:'GCS-10')
Name.create(foil_name:'Brown', pigment_code:'GCS-19')
Length.create(foil_length: '17 Yds')
Length.create(foil_length: '25 Yds')
Length.create(foil_length: '27 Yds')
Length.create(foil_length: '49 Yds')
Length.create(foil_length: '50 Yds')
Length.create(foil_length: '99 Yds')
Make.create(foil_make: 'Gerber Edge I/II')
Make.create(foil_make: 'Gerber Edge FX')
Make.create(foil_make: 'Zero 9 Name')